#!/usr/bin/perl -w
##Version: 0.1
##2017-6-1
##Author: Jingyu Lou @ Bio-X, SJTU
use 5.022;
my $table;
my $index = 1;
my @label;
my $max;
while( <> ) {
	chomp;
	my @line = split;
	$max = @line;
	for( 1..$max ) {
		$table->{$_}->{$index} = $line[$_-1];
	}
	$index++;
}
for( 2..$max ) {
	$table->{$_}->{total} = $table->{$_}->{2} + $table->{$_}->{3};
	delete $table->{$_} if $table->{$_}->{total} == 0;
}
my @sort = sort {
	$table->{$b}->{total} <=> $table->{$a}->{total}
}
	grep { $_ != 1 } keys %{$table};
for my $ln ( 1..3 ) {
	print $table->{1}->{$ln};
	for( @sort ) {
		print "\t$table->{$_}->{$ln}"
	}
	print "\n";
}
